baseURL = "https://blog.daviacandido.com.br/"
title = "daviacandido"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
pagerSize = 6


[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Davi A. Cândido"
description = "Davi's personal website"
keywords = "blog,devsecops,sre,personal"
info = ["DevSecOps and Hobbies"]
avatarURL = "images/avatar.png"
#gravatar = "daviacandido@hotmail.com"
dateFormat = "January 2, 2006"
since = 2026
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = []
customSCSS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/daviacandido/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/daviaraujocandido/"

[languages.en]
languageName = ":uk:"
title = "daviacandido"

[languages.en.params]
author = "Davi A. Cândido"
info = "DevSecOps and Hobbies"
description = "Personal website and blog of Davi A. Cândido. Articles and projects about DevSecOps, Site Reliability Engineering (SRE), cloud-native infrastructure (AWS/Azure), and hobbies."
keywords = "blog,devsecops,personal,sre,kubernetes,aws"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

[languages.pt-br]
languageName = ":brazil:"
title = "daviacandido"

[languages.pt-br.params]
author = "Davi A. Cândido"
info = "DevSecOps e Hobbies"
description = "Site e blog pessoal de Davi A. Cândido. Artigos e projetos sobre DevSecOps, Engenharia de Confiabilidade (SRE), infraestrutura cloud-native (AWS/Azure) e hobbies."
keywords = "blog,devsecops,pessoal,sre,kubernetes,aws"

[[languages.pt-br.menu.main]]
name = "Sobre"
weight = 1
url = "about/"

[[languages.pt-br.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.pt-br.menu.main]]
name = "Contato"
weight = 5
url = "contact/"